public with sharing class OrderTriggerHandler {
    // after insert, after update, after delete, after undelete
    public static void afterInsert() {
        // TODO - implement
    }
    public static void afterUpdate() {
        // TODO - implement
    }
    public static void afterDelete() {
        // TODO - implement
    }
    public static void afterUndelete() {
        // TODO - implement
    }
}